/*
24/05/2023

NOVOS AGREGADORES:

- SUM 
- MAX
- MIN
- AVG
- GROUP BY
- HAVING

*/

USE AdventureWorks2012

-- QUANTOS PRODUTOS VERMELHOS TEM PREÇO ENTRE 500 E 100 --
SELECT COUNT (*) AS 'PRODUTOS VERMELHOS' FROM Production.Product
WHERE Color LIKE 'Red'
AND ListPrice BETWEEN '500' AND '1000'

-- PRODUTOS QUE TEM ESSA ESSA SEQ DE CARACTER NO NOME ROAD --
SELECT * FROM Production.Product
WHERE NAME LIKE '%ROAD%'

-- OU --

SELECT COUNT(NAME) FROM Production.Product
WHERE NAME LIKE '%ROAD%'


SELECT * FROM Sales.SalesOrderDetail

-- O TOP 10 DA TEBELA --
SELECT TOP 10 * FROM Sales.SalesOrderDetail

-- SOMATORIO DO LINE TOTAL --
SELECT * FROM Sales.SalesOrderDetail ORDER BY LineTotal ASC
     -- OU --
SELECT * FROM Sales.SalesOrderDetail ORDER BY LineTotal DESC

-- SOMA TUDO --
SELECT TOP 10 SUM (LineTotal) AS 'TOTAL VENDAS'
FROM Sales.SalesOrderDetail 

-- QUERO SABER QUAL FOI A MAIOR VENDA --
SELECT TOP 10 MAX (LineTotal) AS 'MAXIMO DE VENDAS'
FROM Sales.SalesOrderDetail 

-- QUERO SABER QUAL FOI A MENOR VENDA --
SELECT TOP 10 MIN (LineTotal) AS 'MINIMO DE VENDAS'
FROM Sales.SalesOrderDetail 

-- MEDIA --
SELECT AVG (LineTotal) AS 'MEDIA'
FROM Sales.SalesOrderDetail 

-- Quantas vezes o mesmo nome aparece na tabela --
SELECT FirstName, COUNT(FirstName) AS 'QTDE.' FROM Person.Person
GROUP BY FirstName

SELECT SpecialOfferID, SUM(UnitPrice) AS 'TOTAL DE VENDAS' FROM Sales.SalesOrderDetail
GROUP BY SpecialOfferID
ORDER BY SUM(UnitPrice) DESC

SELECT ProductID, COUNT(ProductID) AS 'QTD PRODT ATE HOJE' FROM Sales.SalesOrderDetail
GROUP BY ProductID

-- PRODUCTION.PRODUCT - PRODUTOS PRATA  MEDIA DE PREÇOS
SELECT COLOR, AVG(ListPrice) FROM Production.Product
WHERE Color = 'Silver'
GROUP BY COLOR

SELECT MiddleName, COUNT(MiddleName) FROM Person.Person
GROUP BY MiddleName
ORDER BY MiddleName


/*1 - QUAL A MEDIA QUE CADA PRODUTO É VENDIDO*/

SELECT ProductID, AVG(OrderQty) FROM Sales.SalesOrderDetail
GROUP BY ProductID

/*2 - QUAIS OS 10 PRODUTOS QUE NO TOTAL TIVERAM OS MAIORES VALORES DE VENDA AGRUPADOS 
POR PRODUTO DO MAIOR PARA O MENOR*/

SELECT TOP 10 ProductID, SUM(LineTotal) FROM Sales.SalesOrderDetail
GROUP BY ProductID
ORDER BY SUM(LineTotal) DESC

/* 3 - QUANTOS PRODUTOS E QUAL A QTDE MEDIA DE PRODUTOS TEMOS CADASTRADOS NAS ORDENS
DE SERVIÇO (WORKORDER) - AGRUPAR PELO ID DO PRODUTO [PRODUCTION.WORKORDER] */

SELECT ProductID, COUNT(ProductID) AS 'QTDE.', AVG(OrderQty) AS 'MEDIA'
FROM Production.WorkOrder
GROUP BY ProductID

-- QUERO OS NOMES QUE APARECEM MAIS DE 10 VEZES --
SELECT FirstName, COUNT(FirstName) FROM Person.Person
GROUP BY FirstName
HAVING COUNT(FirstName) > 10

-- NOMES QUE TERMINAM COM LETRA G --
SELECT FirstName, COUNT(FirstName) FROM Person.Person
WHERE FirstName LIKE '%G'
GROUP BY FirstName
HAVING COUNT(FirstName) > 10

-- AGRUPAR PRODUTOS POR VENDAS TOTAIS ENTRE 162000 E 500000 --
SELECT ProductID, SUM(LineTotal) AS 'TOTAL DE VENDAS' FROM Sales.SalesOrderDetail
GROUP BY ProductID
HAVING SUM(LineTotal) BETWEEN '162000' AND '500000'

-- QUAIS PRODUTOS NÃO ESTÃO TRAZENDO EM MÉDIA VENDAS DE 10000 NO TOTAL --
SELECT ProductID, AVG(LineTotal) FROM Sales.SalesOrderDetail
GROUP BY ProductID
HAVING AVG(LineTotal) < 1000